-- Paiement simulé du certificat + répartition des recettes.
--
-- Règle métier : le citoyen paie au moment où il consulte le document dans
-- « Mes papiers ». Le paiement est unique : une fois réglé, le certificat reste
-- accessible. L'argent est encaissé par l'administration, qui reverse ensuite
-- 90 % au délégué et conserve 10 %.

-- 1. Prix du document, porté par la maison ------------------------------------
-- Fixé par l'administrateur à la création de la maison de chef de quartier.

alter table public.houses
  add column if not exists document_price integer not null default 0;

comment on column public.houses.document_price is
  'Prix du certificat en francs CFA, fixé par l''administrateur à la création de la maison. 0 = document gratuit.';

alter table public.houses
  add constraint houses_document_price_positive check (document_price >= 0) not valid;

-- 2. Paiements ----------------------------------------------------------------
-- Les parts sont figées à l'enregistrement : si le taux de commission change un
-- jour, l'historique déjà encaissé n'est pas réécrit.

do $$ begin
  create type public.payment_provider as enum ('wave', 'orange_money');
exception when duplicate_object then null; end $$;

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  request_id bigint not null unique references public.document_requests(id) on delete cascade,
  citizen_id uuid not null references public.profiles(id) on delete restrict,
  delegate_id uuid references public.profiles(id) on delete set null,
  house_id bigint not null references public.houses(id) on delete restrict,
  provider public.payment_provider not null,
  amount integer not null,
  delegate_amount integer not null,
  platform_amount integer not null,
  delegate_share_percent integer not null default 90,
  reference text not null,
  paid_at timestamptz not null default now(),
  constraint payments_amount_positive check (amount >= 0),
  constraint payments_split_matches check (delegate_amount + platform_amount = amount)
);

comment on table public.payments is
  'Paiement simulé Wave / Orange Money. Une ligne par demande : request_id est unique, le citoyen ne paie qu''une fois.';
comment on column public.payments.delegate_amount is
  'Part reversée au délégué (90 % par défaut), figée au moment du paiement.';
comment on column public.payments.platform_amount is
  'Part conservée par l''administration (10 % par défaut), figée au moment du paiement.';

create index if not exists payments_delegate_idx on public.payments(delegate_id, paid_at desc);
create index if not exists payments_citizen_idx on public.payments(citizen_id, paid_at desc);
create index if not exists payments_paid_at_idx on public.payments(paid_at desc);

-- 3. Sécurité -----------------------------------------------------------------

alter table public.payments enable row level security;

drop policy if exists payments_select on public.payments;
create policy payments_select on public.payments for select to authenticated using (
  citizen_id = (select auth.uid())
  or delegate_id = (select auth.uid())
  or public.current_user_role() = 'admin'
);

-- L'insertion passe uniquement par l'API (service_role) : elle seule calcule le
-- montant à partir du prix de la maison. Aucune policy d'insert pour les
-- utilisateurs authentifiés, sinon un citoyen pourrait déclarer avoir payé 0 F.

grant select on public.payments to authenticated;
grant all on public.payments to service_role;
grant usage, select on all sequences in schema public to authenticated;
