-- Sunu Papiers - schema Supabase initial
-- A executer dans Supabase SQL Editor sur un projet neuf.

create extension if not exists pgcrypto;

do $$ begin
  create type public.user_role as enum ('admin', 'delegate', 'citizen');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.request_status as enum ('pending', 'processing', 'approved', 'rejected');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'citizen',
  first_name text not null default '',
  last_name text not null default '',
  phone text unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_phone_format check (phone is null or phone ~ '^[0-9]{9}$')
);

create table if not exists public.citizen_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  father_first_name text not null default '',
  father_last_name text not null default '',
  mother_first_name text not null default '',
  mother_last_name text not null default '',
  birth_date date,
  birth_place text not null default '',
  identity_number text not null default '',
  villa_number text not null default '',
  id_front_path text,
  id_back_path text,
  quartier text not null default '',
  resident_since_year integer,
  updated_at timestamptz not null default now(),
  constraint citizen_resident_year check (resident_since_year is null or resident_since_year between 1900 and 2100)
);

create table if not exists public.houses (
  id bigint generated by default as identity primary key,
  region text not null,
  departement text not null,
  commune text not null,
  quartier text not null,
  delegate_id uuid references public.profiles(id) on delete set null,
  certificate_path text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint houses_region_upper check (region = upper(region)),
  constraint houses_departement_upper check (departement = upper(departement)),
  constraint houses_commune_upper check (commune = upper(commune)),
  constraint houses_quartier_upper check (quartier = upper(quartier))
);

create unique index if not exists houses_active_quartier_unique
  on public.houses (upper(quartier)) where active;
create unique index if not exists houses_active_delegate_unique
  on public.houses (delegate_id) where active and delegate_id is not null;

create table if not exists public.document_requests (
  id bigint generated by default as identity primary key,
  reference text unique,
  citizen_id uuid not null references public.profiles(id) on delete restrict,
  house_id bigint not null references public.houses(id) on delete restrict,
  delegate_id uuid references public.profiles(id) on delete set null,
  document_type text not null default 'Certificat de domicile',
  status public.request_status not null default 'pending',
  address text not null,
  birth_date date,
  birth_place text not null default '',
  identity_number text not null default '',
  lot_number text not null default '',
  certificate_path text,
  submitted_at timestamptz not null default now(),
  processed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists document_requests_citizen_idx on public.document_requests(citizen_id, submitted_at desc);
create index if not exists document_requests_delegate_idx on public.document_requests(delegate_id, status, submitted_at desc);
create index if not exists document_requests_house_idx on public.document_requests(house_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
drop trigger if exists citizen_profiles_set_updated_at on public.citizen_profiles;
create trigger citizen_profiles_set_updated_at before update on public.citizen_profiles
for each row execute function public.set_updated_at();
drop trigger if exists houses_set_updated_at on public.houses;
create trigger houses_set_updated_at before update on public.houses
for each row execute function public.set_updated_at();
drop trigger if exists requests_set_updated_at on public.document_requests;
create trigger requests_set_updated_at before update on public.document_requests
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  assigned_role public.user_role;
begin
  assigned_role := case
    when new.raw_app_meta_data ->> 'role' in ('admin', 'delegate')
      then (new.raw_app_meta_data ->> 'role')::public.user_role
    else 'citizen'::public.user_role
  end;

  insert into public.profiles(id, role, first_name, last_name, phone)
  values (
    new.id,
    assigned_role,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', ''),
    nullif(regexp_replace(coalesce(new.phone, new.raw_user_meta_data ->> 'phone', ''), '\D', '', 'g'), '')
  );

  if assigned_role = 'citizen' then
    insert into public.citizen_profiles(user_id) values (new.id);
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.prepare_document_request()
returns trigger language plpgsql security definer set search_path = '' as $$
declare selected_house public.houses%rowtype;
begin
  select * into selected_house from public.houses where id = new.house_id and active;
  if not found then raise exception 'Maison introuvable ou archivee'; end if;
  if selected_house.delegate_id is null then raise exception 'Aucun delegue affecte a cette maison'; end if;
  new.delegate_id := selected_house.delegate_id;
  new.reference := 'CD-' || extract(year from now() at time zone 'Africa/Dakar')::integer || '-' || lpad(new.id::text, 4, '0');
  return new;
end;
$$;

drop trigger if exists document_request_prepare on public.document_requests;
create trigger document_request_prepare before insert on public.document_requests
for each row execute function public.prepare_document_request();

create or replace function public.current_user_role()
returns public.user_role language sql stable security definer set search_path = '' as $$
  select role from public.profiles where id = (select auth.uid()) and active;
$$;

create or replace function public.protect_profile_security_fields()
returns trigger language plpgsql set search_path = '' as $$
begin
  if (old.role, old.active) is distinct from (new.role, new.active)
     and current_user not in ('postgres', 'service_role', 'supabase_admin')
     and coalesce(public.current_user_role(), 'citizen'::public.user_role) <> 'admin' then
    raise exception 'Seul un administrateur peut modifier le role ou le statut';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_protect_security_fields on public.profiles;
create trigger profiles_protect_security_fields before update on public.profiles
for each row execute function public.protect_profile_security_fields();

alter table public.profiles enable row level security;
alter table public.citizen_profiles enable row level security;
alter table public.houses enable row level security;
alter table public.document_requests enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using (
  id = (select auth.uid()) or public.current_user_role() = 'admin' or
  (public.current_user_role() = 'delegate' and exists (
    select 1 from public.document_requests r where r.citizen_id = profiles.id and r.delegate_id = (select auth.uid())
  ))
);
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update to authenticated
using (id = (select auth.uid()) or public.current_user_role() = 'admin')
with check (id = (select auth.uid()) or public.current_user_role() = 'admin');

drop policy if exists citizen_profiles_select on public.citizen_profiles;
create policy citizen_profiles_select on public.citizen_profiles for select to authenticated using (
  user_id = (select auth.uid()) or public.current_user_role() = 'admin' or
  (public.current_user_role() = 'delegate' and exists (
    select 1 from public.document_requests r where r.citizen_id = citizen_profiles.user_id and r.delegate_id = (select auth.uid())
  ))
);
drop policy if exists citizen_profiles_update on public.citizen_profiles;
create policy citizen_profiles_update on public.citizen_profiles for update to authenticated
using (user_id = (select auth.uid()) or public.current_user_role() = 'admin')
with check (user_id = (select auth.uid()) or public.current_user_role() = 'admin');

drop policy if exists houses_select on public.houses;
create policy houses_select on public.houses for select to authenticated using (
  active or public.current_user_role() = 'admin' or exists (
    select 1 from public.document_requests r where r.house_id = houses.id and (r.citizen_id = (select auth.uid()) or r.delegate_id = (select auth.uid()))
  )
);
drop policy if exists houses_admin_insert on public.houses;
create policy houses_admin_insert on public.houses for insert to authenticated with check (public.current_user_role() = 'admin');
drop policy if exists houses_admin_update on public.houses;
create policy houses_admin_update on public.houses for update to authenticated
using (public.current_user_role() = 'admin') with check (public.current_user_role() = 'admin');

drop policy if exists requests_select on public.document_requests;
create policy requests_select on public.document_requests for select to authenticated using (
  citizen_id = (select auth.uid()) or delegate_id = (select auth.uid()) or public.current_user_role() = 'admin'
);
drop policy if exists requests_citizen_insert on public.document_requests;
create policy requests_citizen_insert on public.document_requests for insert to authenticated with check (
  citizen_id = (select auth.uid()) and public.current_user_role() = 'citizen'
);
drop policy if exists requests_delegate_update on public.document_requests;
create policy requests_delegate_update on public.document_requests for update to authenticated
using (delegate_id = (select auth.uid()) or public.current_user_role() = 'admin')
with check (delegate_id = (select auth.uid()) or public.current_user_role() = 'admin');

grant select, update on public.profiles to authenticated;
grant select, update on public.citizen_profiles to authenticated;
grant select, insert, update on public.houses to authenticated;
grant select, insert, update on public.document_requests to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant all on public.profiles, public.citizen_profiles, public.houses, public.document_requests to service_role;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values
  ('identity-documents', 'identity-documents', false, 8388608, array['image/jpeg','image/png','image/webp']),
  ('house-templates', 'house-templates', false, 8388608, array['application/pdf']),
  ('generated-certificates', 'generated-certificates', false, 12582912, array['application/pdf'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists identity_owner_select on storage.objects;
create policy identity_owner_select on storage.objects for select to authenticated using (
  bucket_id = 'identity-documents' and (
    (storage.foldername(name))[1] = (select auth.uid())::text or public.current_user_role() = 'admin' or
    (public.current_user_role() = 'delegate' and exists (
      select 1 from public.document_requests r
      where r.citizen_id::text = (storage.foldername(name))[1] and r.delegate_id = (select auth.uid())
    ))
  )
);
drop policy if exists identity_owner_insert on storage.objects;
create policy identity_owner_insert on storage.objects for insert to authenticated with check (
  bucket_id = 'identity-documents' and (storage.foldername(name))[1] = (select auth.uid())::text
);
drop policy if exists identity_owner_update on storage.objects;
create policy identity_owner_update on storage.objects for update to authenticated
using (bucket_id = 'identity-documents' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'identity-documents' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists templates_read on storage.objects;
create policy templates_read on storage.objects for select to authenticated using (
  bucket_id = 'house-templates' and public.current_user_role() in ('admin','delegate')
);
drop policy if exists templates_admin_insert on storage.objects;
create policy templates_admin_insert on storage.objects for insert to authenticated with check (
  bucket_id = 'house-templates' and public.current_user_role() = 'admin'
);
drop policy if exists templates_admin_update on storage.objects;
create policy templates_admin_update on storage.objects for update to authenticated
using (bucket_id = 'house-templates' and public.current_user_role() = 'admin')
with check (bucket_id = 'house-templates' and public.current_user_role() = 'admin');

drop policy if exists certificates_read on storage.objects;
create policy certificates_read on storage.objects for select to authenticated using (
  bucket_id = 'generated-certificates' and (
    (storage.foldername(name))[1] = (select auth.uid())::text or public.current_user_role() = 'admin' or
    (public.current_user_role() = 'delegate' and exists (
      select 1 from public.document_requests r
      where r.citizen_id::text = (storage.foldername(name))[1] and r.delegate_id = (select auth.uid())
    ))
  )
);

create or replace view public.admin_dashboard with (security_invoker = true) as
select
  (select count(*) from public.profiles where role = 'citizen' and active) as citizens,
  (select count(*) from public.profiles where role = 'delegate' and active) as delegates,
  (select count(*) from public.houses where active) as houses,
  (select count(*) from public.document_requests) as requests,
  (select count(*) from public.document_requests where status = 'pending') as pending;

grant select on public.admin_dashboard to authenticated;

-- Apres avoir cree le premier utilisateur dans Authentication > Users :
-- update auth.users set raw_app_meta_data = raw_app_meta_data || '{"role":"admin"}'::jsonb where email = 'admin@exemple.sn';
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'admin@exemple.sn');
